max-blocks: 64
require-sneak: true

mineable-blocks:
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - REDSTONE_ORE
  - LAPIS_ORE
  - EMERALD_ORE
  - NETHER_QUARTZ_ORE
  - ANCIENT_DEBRIS
